## CREATE USERS
POST http://localhost:8000/users
Content-Type: application/json

 {
  "username": "exaasdasdmasdpleUser",
  "password": "examasdasdasdplePass",
  "email": "exaasasdasddmple@example.com"
}


## GET USERS
# GET http://localhost:8000/users
