# # CREATE USERS
# POST http://localhost:8000/users
# Content-Type: application/json

#  {
#   "username": "exaasdasdmasdpleUser",
#   "password": "examasdasdasdplePass",
#   "email": "exaasasdasddmple@example.com"
# }


# GET USERS
# GET http://localhost:8000/transaction/132

POST http://localhost:8000/transaction/132
Content-Type: application/json

 {
  "type": "expense",
  "amount": 2000,
  "category": "Transporte",
  "date": "2025-02-09",
  "description": "Gasolina"
}